# Generated by Django 2.1.2 on 2018-10-20 12:09

import django.contrib.postgres.fields
from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=report.models.report_location), blank=True, size=None),
        ),
    ]
