# Generated by Django 2.1.2 on 2018-10-21 07:27

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181020_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='photos',
        ),
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, upload_to=report.models.report_location),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Rejected'), (2, 'Accepted')], default=0),
        ),
    ]
